load('../../data/input/holograms/opt_Warsaw_Lowiczanka_Doll.mat');

info = getSettings('cfg_file', './../data/config/nrsh_config/wut/lowiczanka_doll_000.txt', ...
    'dataset', 'wut_disp', ...
    'apertureinpxmode', true, ...
    'ap_sizes', {[2000, 3000], [2000, 6000], [0, 0]}, ...
    'h_pos', 1, 'v_pos', 0, ...
    'resize_fun', 'DR');
