load("../../data/input/holograms/opt_Warsaw_Lowiczanka_Doll.mat");

ap_sizes = [2000 3000];
out_dir = sprintf("./lowiczanka_doll_[%dx%d]/", ap_sizes(1), ap_sizes(2));

info = getSettings('cfg_file', '../../data/config/nrsh_config/wut/lowiczanka_doll_000.txt', ...
    'dataset', 'wut_disp_on_axis', ...
    'apertureinpxmode', true, ...
    'ap_sizes', ap_sizes, ...
    'h_pos', 1, 'v_pos', 0, ...
    'targetres', [2016 59394], ...
    'usagemode', 'exhaustive', ...
    'resize_fun', 'DR');

nrsh(dh, 1.06, info);
