clear;clc

load("../../data/input/holograms/opt_Warsaw_Lowiczanka_Doll.mat");

info = getSettings('cfg_file', '../../data/config/nrsh_config/wut/lowiczanka_doll_000.txt', ...
    'dataset', 'wut_disp_on_axis', ...
    'apertureinpxmode', true, ...
    'targetres', [2016 2016], ...
    'h_pos', 1, 'v_pos', 0, ...
    'resize_fun', 'DR');

nrsh(dh, 1.06, info);