hologram_path = '../../data/input/holograms/CGH_Biplane16k_rgb.mat';
config_path = '../../data/config/nrsh_config/interfereIII/biplane16kETRO_000.txt';

load(hologram_path)

info = getSettings('cfg_file', config_path, ...
    'apertureinpxmode', true, ...
    'ap_sizes', [2048 2048], ...
    'h_pos', [0 1], ...
    'v_pos', [0 1]);

nrsh(double(data.CGH.Hol), 0.0455, info)
