hologram_path = '../../data/input/holograms/breakdancers8k4k_022.mat';
config_path = '../../data/config/nrsh_config/bcom/breakdancers8k4k_000.txt';

load(hologram_path)

info = getSettings('cfg_file', config_path, ...
    'apertureinpxmode', true, ...
    'ap_sizes', [7680 4320], ...
    'h_pos', [0], ...
    'v_pos', [0]);

nrsh(double(data), 0.025, info)
