hologram_path = '../../data/input/holograms/DeepDices2K.mat';
config_path = '../../data/config/nrsh_config/bcom/DeepDices2k_000.txt';

load(hologram_path)

info = getSettings('cfg_file', config_path, ...
    'apertureinpxmode', true, ...
    'ap_sizes', [2048 2048], ...
    'h_pos', [0], ...
    'v_pos', [0]);

nrsh(double(data), 0.867, info)
