hologram_path = '../../data/input/holograms/Dices16K.mat';
config_path = '../../data/config/nrsh_config/bcom/dices16k_000.txt';

load(hologram_path)

info = getSettings('cfg_file', config_path, ...
    'apertureinpxmode', true, ...
    'ap_sizes', [2048 2048], ...
    'h_pos', [0 1], ...
    'v_pos', [0 1]);

nrsh(double(data), 0.01, info)
