load('/mnt/data/code/Single-Phase-Reconstruction/data/input/holograms/specularCar8k.mat')

info = getSettings('cfg_file', '/mnt/data/code/Single-Phase-Reconstruction/data/config/nrsh_config/bcom/specular_car8k_000.txt', ...
    'apertureinpxmode', false, ...
    'ap_sizes', 7, ...
    'h_pos', -10:10:10, ...
    'v_pos', -8:8:8);

nrsh(data, 0.0023, info)
