load('/mnt/data/code/Single-Phase-Reconstruction/data/input/holograms/specularCar8k.mat')

info = getSettings('cfg_file', '/mnt/data/code/Single-Phase-Reconstruction/data/config/nrsh_config/bcom/specular_car8k_000.txt', ...
    'apertureinpxmode', true, ...
    'ap_sizes', [4096 4096], ...
    'h_pos', [0 1], ...
    'v_pos', 0);

nrsh(data, 0.0023, info)
