load('CGH_Biplane16K.mat');

info = getSettings('cfg_file', 'config_files/interfereIII/biplane16k_000.txt', ...
    'dataset', 'interfere', ...
    'apertureinpxmode', false, ...
    'ap_sizes', [1, 2, 4], ...
    'resize_fun', @(x) imresize(x, [2048 1024], 'bilinear'));

nrsh(CGH.Hol, 0.037, info);
