info = getSettings('cfg_file', 'config_files/interfereIV/chess2_000.txt', ...
    'apertureinpxmode', true, ...
    'ap_sizes', {[1792, 1792]}, ...
    'h_pos', [-1, 0, 1]);
nrsh('./data/Squirrel', 0.535, info);
