hologram_path = 'specularCar8k.mat';
config_path = 'config_files/bcom/specular_car8k_000.txt';

load(hologram_path)

info = getSettings('cfg_file', config_path, ...
    'apertureinpxmode', false, ...
    'ap_sizes', 7, ...
    'h_pos', -10:10:10, ...
    'v_pos', -8:8:8);

nrsh(data, 0.0023, info)
