load('/mnt/data/code/Single-Phase-Reconstruction/data/input/holograms/deepDices16k.mat')

info = getSettings('cfg_file', '/mnt/data/code/Single-Phase-Reconstruction/data/config/nrsh_config/bcom/DeepDices16k_000.txt', ...
    'ap_sizes', {[2048 2048] [4096 4096]}, ...
    'h_pos', [-1 0 1], ...
    'v_pos', 0);

nrsh(data, 0.0185, info)
