load('/mnt/data/code/Single-Phase-Reconstruction/data/input/holograms/deepDices8k4k.mat')

info = getSettings('cfg_file', '/mnt/data/code/Single-Phase-Reconstruction/data/config/nrsh_config/bcom/DeepDices8k4k_000.txt', ...
    'resize_fun', 'DR', ...
    'ap_sizes', [4320 7680],  ...
    'targetres', [4320 7680],  ...
    'h_pos', [-1 0 1], ...
    'v_pos', [0]);

nrsh(data, 0.331, info)