%% Set Paths
clear; clc

working_dir = working_dir();

add_paths(working_dir, ["src/" "res/nrsh/" "res/nrsh/core/"]);

cfg_dir = [working_dir 'data/config/nrsh_config/'];
save_dir = [working_dir 'data/config/single_phase_config/'];
hologram_dir = [working_dir 'data/input/holograms/'];

holograms = ["CGH_Biplane16k_rgb", "CGH_Venus", "DeepDices16K", "Lowiczanka_Doll", "DeepDices2K", "DeepDices8K4K"];

for holo_name = holograms

    switch holo_name
        case "CGH_Biplane16k_rgb"
            disp("Creating CGH_Biplane16k_rgb")
            hologram_path = [hologram_dir 'CGH_Biplane16k_rgb.mat'];
            cfg_file = [cfg_dir 'interfereIII/biplane16kETRO_000.txt'];

            %% Load config

            dataset = 'interfere';
            zero_pad = false;
            usagemode = 'individual';
            h_pos = 0;
            v_pos = 0;
            ap_sizes = [16384 16384];
            target_res = [16384 16384];
            default_rec_dist = 0.0455;

            info = getSettings('dataset', dataset, ...
                'zero_pad', zero_pad, ...
                'cfg_file', cfg_file, ...
                'usagemode', usagemode, ...
                'ap_sizes', ap_sizes, ...
                'apertureinpxmode', true, ...
                'h_pos', h_pos, ...
                'v_pos', v_pos, ...
                'targetres', target_res, ...
                'direction', 'forward', ...
                'resize_fun', 'DR');

            save([save_dir 'Biplane16k_config.mat'], ...
                'default_rec_dist', ...
                'info', ...
            'hologram_path');

        case "CGH_Venus"
            hologram_path = [hologram_dir 'CGH_Venus.mat'];
            cfg_file = [cfg_dir 'interfereIII/venus_000.txt'];

            %% Load config

            dataset = 'interfere';
            zero_pad = false;
            usagemode = 'individual';
            h_pos = 0.5;
            v_pos = 0.5;
            ap_sizes = [2048 2048];
            target_res = [2048 2048];
            default_rec_dist = 0.2957;

            info = getSettings('dataset', dataset, ...
                'zero_pad', zero_pad, ...
                'cfg_file', cfg_file, ...
                'usagemode', usagemode, ...
                'ap_sizes', ap_sizes, ...
                'apertureinpxmode', true, ...
                'h_pos', h_pos, ...
                'v_pos', v_pos, ...
                'targetres', target_res, ...
                'direction', 'forward', ...
                'resize_fun', 'DR');

            save([save_dir 'CGH_Venus_config.mat'], ...
                'default_rec_dist', ...
                'info', ...
            'hologram_path');

        case "DeepDices16K"
            hologram_path = [hologram_dir 'DeepDices16K.mat'];
            cfg_file = [cfg_dir 'bcom/DeepDices2k_000.txt'];

            %% Load config

            dataset = 'bcom32';
            zero_pad = false;
            usagemode = 'individual';
            h_pos = 0;
            v_pos = 0;
            ap_sizes = [16384 16384];
            target_res = [16384 16384];
            default_rec_dist = 0.0185;

            info = getSettings('dataset', dataset, ...
                'zero_pad', zero_pad, ...
                'cfg_file', cfg_file, ...
                'usagemode', usagemode, ...
                'ap_sizes', ap_sizes, ...
                'apertureinpxmode', true, ...
                'h_pos', h_pos, ...
                'v_pos', v_pos, ...
                'targetres', target_res, ...
                'direction', 'forward', ...
                'resize_fun', 'DR');

            save([save_dir 'DeepDices16K_config.mat'], ...
                'default_rec_dist', ...
                'info', ...
            'hologram_path');

        case "DeepDices2K"
            hologram_path = [hologram_dir 'deepDices2k.mat'];
            cfg_file = [cfg_dir 'bcom/DeepDices2k_000.txt'];

            %% Load config

            dataset = 'bcom32';
            zero_pad = false;
            usagemode = 'individual';
            h_pos = 0;
            v_pos = 0;
            ap_sizes = [2048 2048];
            target_res = [2048 2048];
            default_rec_dist = 0.087;

            info = getSettings('dataset', dataset, ...
                'zero_pad', zero_pad, ...
                'cfg_file', cfg_file, ...
                'usagemode', usagemode, ...
                'ap_sizes', ap_sizes, ...
                'apertureinpxmode', true, ...
                'h_pos', h_pos, ...
                'v_pos', v_pos, ...
                'targetres', target_res, ...
                'direction', 'forward', ...
                'resize_fun', 'DR');

            save([save_dir 'DeepDices2K_config.mat'], ...
                'default_rec_dist', ...
                'info', ...
            'hologram_path');

        case "DeepDices8K4K"
            hologram_path = [hologram_dir 'deepDices8k4k.mat'];
            cfg_file = [cfg_dir 'bcom/DeepDices8k4k_000.txt'];

            %% Load config

            dataset = 'bcom32';
            zero_pad = false;
            usagemode = 'individual';
            h_pos = 0;
            v_pos = 0;
            ap_sizes = [4320 7680];
            target_res = [4096 4096];
            default_rec_dist = 0.3;

            info = getSettings('dataset', dataset, ...
                'zero_pad', zero_pad, ...
                'cfg_file', cfg_file, ...
                'usagemode', usagemode, ...
                'ap_sizes', ap_sizes, ...
                'apertureinpxmode', true, ...
                'h_pos', h_pos, ...
                'v_pos', v_pos, ...
                'targetres', target_res, ...
                'direction', 'forward', ...
                'resize_fun', 'DR');

            save([save_dir 'DeepDices8K4K_config.mat'], ...
                'default_rec_dist', ...
                'info', ...
            'hologram_path');

        case "Lowiczanka_Doll"
            hologram_path = [hologram_dir 'opt_Warsaw_Lowiczanka_Doll.mat'];
            cfg_file = [cfg_dir 'wut/lowiczanka_doll_000.txt'];

            %% Load config

            dataset = 'wut_disp_on_axis';
            zero_pad = false;
            usagemode = 'individual';
            h_pos = [-1 0 1];
            v_pos = 0;
            ap_sizes = [2016 2016];
            target_res = [2016 2016];
            default_rec_dist = [1.060 1.030 1.075];

            info = getSettings('dataset', dataset, ...
                'zero_pad', zero_pad, ...
                'cfg_file', cfg_file, ...
                'usagemode', usagemode, ...
                'ap_sizes', ap_sizes, ...
                'apertureinpxmode', true, ...
                'h_pos', h_pos, ...
                'v_pos', v_pos, ...
                'targetres', target_res, ...
                'direction', 'forward', ...
                'resize_fun', 'DR');
            info.isFourierDH = 1;
            info.clip_max = -1;
            info.clip_min = -1;

            save([save_dir 'Lowiczanka_Doll_config.mat'], ...
                'default_rec_dist', ...
                'info', ...
            'hologram_path');

        otherwise
            disp('Hologram config missing')
    end

end
