clear; clc
pwd()
%% Set Paths
add_paths('../', ["res/nrsh/" ...
                         "res/nrsh/core/" ...
                         "res/nrsh/core/WUT_lib/" ...
                         "src/" ...
                         "src/reconstruction/" ...
                         "src/utils/"
                     ])

info = getSettings( ...
    'cfg_file', '../data/config/nrsh_config/bcom/DeepDices8k4k_000.txt', ...
    'resize_fun', 'DR', ...
    'targetres', [2160 3840], ...
    'h_pos', [-1 0 1], ...
    'v_pos', [-1 0 1]);

holo = load('../data/input/holograms/deepDices8k4k.mat');
nrsh(holo.data, 0.331, info, 'exhaustive');
